name: Publish Torizon Utils
on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Xonsh
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip pipx
          sudo bash ./scripts/bash/setup-xonsh.sh
          sudo ln -s /root/.local/bin/xonsh /usr/bin/xonsh

      - name: Build
        run: |
          echo "${{ secrets.DOCKER_PASS }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          cd ./scripts
          xonsh ./build-internal-containers.xsh
