name: Publish Torizon Utils
on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Sanity version
        run: |
          # read the toml
          version=$(cat ./scripts/utils/pip/pyproject.toml | grep version | cut -d '"' -f 2)
          # check with the latest version published on pypi
          latest_version=$(curl -s https://pypi.org/pypi/torizon-templates-utils/json | jq -r '.info.version')

          if [ "$version" == "$latest_version" ]; then
            echo "Version $version is already published on PyPI"
            echo "SKIP_PUBLISH=true" >> $GITHUB_ENV
          else
            echo "Version $version is not published on PyPI"
            echo "SKIP_PUBLISH=false" >> $GITHUB_ENV
          fi

      - name: Setup Python
        if: env.SKIP_PUBLISH != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            python3-venv \
            python3-setuptools \
            python3-build \
            pipx \
            twine

      - name: Create Package
        if: env.SKIP_PUBLISH != 'true'
        run: |
          cd ./scripts/utils/pip
          python3 -m build

      - name: Create .pypirc
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.PYPI_CREDS }}
        run: |
          echo "[pypi]" > ./scripts/utils/pip/.pypirc
          echo "username = $TWINE_USERNAME" >> ./scripts/utils/pip/.pypirc
          echo "password = $TWINE_PASSWORD" >> ./scripts/utils/pip/.pypirc

      - name: Publish Package
        run: |
          cd ./scripts/utils/pip
          python3 -m \
            twine \
              upload \
              --config-file .pypirc \
              dist/*
